### ISSUE TITLE
Fail to install admix-kit 

### ISSUE THREAD

**Issue by xiw588** [KangchengHou/admix-kit#23]
**Describe the bug**
I try to install admix-kit following the instructions. I update the cmake first but it turns out to be using the old version, I guess?

**To Reproduce**
cd admix-kit && pip install -e .

**Screenshots**
ERROR: Command errored out with exit status 1:
   command: /n/sw/eb/apps/centos7/Anaconda3/2020.11/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-_1ohrzxs/tinygwas/setup.py'"'"'; __file__='"'"'/tmp/pip-install-_1ohrzxs/tinygwas/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-f_9vj7u1
       cwd: /tmp/pip-install-_1ohrzxs/tinygwas/
  Complete output (39 lines):
  running bdist_wheel
  running build
  running build_ext
  CMake Error at CMakeLists.txt:1 (cmake_minimum_required):
    CMake 3.12 or higher is required.  You are running version 2.8.12.2
  
  
  -- Configuring incomplete, errors occurred!
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-_1ohrzxs/tinygwas/setup.py", line 74, in <module>
      setup(
    File "/n/sw/eb/apps/centos7/Anaconda3/2020.11/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/n/sw/eb/apps/centos7/Anaconda3/2020.11/lib/python3.8/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/n/sw/eb/apps/centos7/Anaconda3/2020.11/lib/python3.8/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/n/sw/eb/apps/centos7/Anaconda3/2020.11/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/n/sw/eb/apps/centos7/Anaconda3/2020.11/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 290, in run
      self.run_command('build')
    File "/n/sw/eb/apps/centos7/Anaconda3/2020.11/lib/python3.8/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/n/sw/eb/apps/centos7/Anaconda3/2020.11/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/n/sw/eb/apps/centos7/Anaconda3/2020.11/lib/python3.8/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/n/sw/eb/apps/centos7/Anaconda3/2020.11/lib/python3.8/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/n/sw/eb/apps/centos7/Anaconda3/2020.11/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-install-_1ohrzxs/tinygwas/setup.py", line 36, in run
      self.build_extension(ext)
    File "/tmp/pip-install-_1ohrzxs/tinygwas/setup.py", line 65, in build_extension
      subprocess.check_call(
    File "/n/sw/eb/apps/centos7/Anaconda3/2020.11/lib/python3.8/subprocess.py", line 364, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['cmake', '/tmp/pip-install-_1ohrzxs/tinygwas', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/tmp/pip-install-_1ohrzxs/tinygwas/build/lib.linux-x86_64-3.8', '-DPYTHON_EXECUTABLE=/n/sw/eb/apps/centos7/Anaconda3/2020.11/bin/python', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.
  ----------------------------------------
  ERROR: Failed building wheel for tinygwas
  Running setup.py clean for tinygwas
  Building wheel for pylampld (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /n/sw/eb/apps/centos7/Anaconda3/2020.11/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-_1ohrzxs/pylampld/setup.py'"'"'; __file__='"'"'/tmp/pip-install-_1ohrzxs/pylampld/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-v_wd4m4h
       cwd: /tmp/pip-install-_1ohrzxs/pylampld/
  Complete output (39 lines):
  running bdist_wheel
  running build
  running build_ext
  CMake Error at CMakeLists.txt:1 (cmake_minimum_required):
    CMake 3.12 or higher is required.  You are running version 2.8.12.2
  
  
  -- Configuring incomplete, errors occurred!
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-_1ohrzxs/pylampld/setup.py", line 69, in <module>
      setup(
    File "/n/sw/eb/apps/centos7/Anaconda3/2020.11/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/n/sw/eb/apps/centos7/Anaconda3/2020.11/lib/python3.8/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/n/sw/eb/apps/centos7/Anaconda3/2020.11/lib/python3.8/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/n/sw/eb/apps/centos7/Anaconda3/2020.11/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/n/sw/eb/apps/centos7/Anaconda3/2020.11/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 290, in run
      self.run_command('build')
    File "/n/sw/eb/apps/centos7/Anaconda3/2020.11/lib/python3.8/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/n/sw/eb/apps/centos7/Anaconda3/2020.11/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/n/sw/eb/apps/centos7/Anaconda3/2020.11/lib/python3.8/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/n/sw/eb/apps/centos7/Anaconda3/2020.11/lib/python3.8/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/n/sw/eb/apps/centos7/Anaconda3/2020.11/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-install-_1ohrzxs/pylampld/setup.py", line 34, in run
      self.build_extension(ext)
    File "/tmp/pip-install-_1ohrzxs/pylampld/setup.py", line 62, in build_extension
      subprocess.check_call(['cmake', ext.sourcedir] + cmake_args,
    File "/n/sw/eb/apps/centos7/Anaconda3/2020.11/lib/python3.8/subprocess.py", line 364, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['cmake', '/tmp/pip-install-_1ohrzxs/pylampld', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/tmp/pip-install-_1ohrzxs/pylampld/build/lib.linux-x86_64-3.8', '-DPYTHON_EXECUTABLE=/n/sw/eb/apps/centos7/Anaconda3/2020.11/bin/python', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.
  ----------------------------------------
  ERROR: Failed building wheel for pylampld
  Running setup.py clean for pylampld
Failed to build tinygwas pylampld
Installing collected packages: tinygwas, pylampld, admix-kit
    Running setup.py install for tinygwas ... error
    ERROR: Command errored out with exit status 1:
     command: /n/sw/eb/apps/centos7/Anaconda3/2020.11/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-_1ohrzxs/tinygwas/setup.py'"'"'; __file__='"'"'/tmp/pip-install-_1ohrzxs/tinygwas/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-s0fxgx4d/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /n/home13/xinanwang/.local/include/python3.8/tinygwas
         cwd: /tmp/pip-install-_1ohrzxs/tinygwas/
    Complete output (41 lines):
    running install
    running build
    running build_ext
    CMake Error at CMakeLists.txt:1 (cmake_minimum_required):
      CMake 3.12 or higher is required.  You are running version 2.8.12.2
    
    
    -- Configuring incomplete, errors occurred!
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-_1ohrzxs/tinygwas/setup.py", line 74, in <module>
        setup(
      File "/n/sw/eb/apps/centos7/Anaconda3/2020.11/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/n/sw/eb/apps/centos7/Anaconda3/2020.11/lib/python3.8/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/n/sw/eb/apps/centos7/Anaconda3/2020.11/lib/python3.8/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/n/sw/eb/apps/centos7/Anaconda3/2020.11/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/n/sw/eb/apps/centos7/Anaconda3/2020.11/lib/python3.8/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/n/sw/eb/apps/centos7/Anaconda3/2020.11/lib/python3.8/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/n/sw/eb/apps/centos7/Anaconda3/2020.11/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/n/sw/eb/apps/centos7/Anaconda3/2020.11/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/n/sw/eb/apps/centos7/Anaconda3/2020.11/lib/python3.8/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/n/sw/eb/apps/centos7/Anaconda3/2020.11/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/n/sw/eb/apps/centos7/Anaconda3/2020.11/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/tmp/pip-install-_1ohrzxs/tinygwas/setup.py", line 36, in run
        self.build_extension(ext)
      File "/tmp/pip-install-_1ohrzxs/tinygwas/setup.py", line 65, in build_extension
        subprocess.check_call(
      File "/n/sw/eb/apps/centos7/Anaconda3/2020.11/lib/python3.8/subprocess.py", line 364, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['cmake', '/tmp/pip-install-_1ohrzxs/tinygwas', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/tmp/pip-install-_1ohrzxs/tinygwas/build/lib.linux-x86_64-3.8', '-DPYTHON_EXECUTABLE=/n/sw/eb/apps/centos7/Anaconda3/2020.11/bin/python', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: /n/sw/eb/apps/centos7/Anaconda3/2020.11/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-_1ohrzxs/tinygwas/setup.py'"'"'; __file__='"'"'/tmp/pip-install-_1ohrzxs/tinygwas/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-s0fxgx4d/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /n/home13/xinanwang/.local/include/python3.8/tinygwas Check the logs for full command output.

**Additional context**

**Comment by xiw588** [comment]
I checked the version right after updating cmake, it still showed to be cmake version 2.8.12.2

**Comment by KangchengHou** [comment]
Yes it is the issue of cmake version. The key is to make sure cmake > 3.12 is installed and `which cmake` shows that.
You may try:
1. find the new version of installed cmake bin and add that to $PATH: `export $PATH=$PATH:/path/to/new/cmake`
2. if you are on a computing cluster, do you have something like `module load`? you may try look at `module avail cmake`
3. maybe ask the system administrater for that

**Comment by xiw588** [comment]
Hi Kangcheng, 

Thank you for our swift response and help! I was unable to run through git clone https://github.com/KangchengHou/admix-kit now. But the error message "ERROR: File "setup.py" not found. Directory cannot be installed in editable mode: /n/home13/XXX" pop up when I tried to run cd admix-kit & pip install -e . I do have setup.py in /n/home13/XXX/admix-kit, and it is allowed to write. Do you know what is wrong there? Thanks!
