### ISSUE TITLE
Index of df_indiv does not match the columns of lanc

### ISSUE THREAD

**Issue by michaelofrancis** [KangchengHou/admix-kit#27]
**Describe the bug**
Hi, I am running admix lanc-convert with pfile and msp, the msp spans the entire chr1 and the pfile is a shard of chr1, not sure if that matters, but I get the following error after running for ~1 hour :

df_snp["POS"][-1] + 1, df_rfmix_info.loc[len(df_rfmix_info) - 1, "epos"]
Traceback (most recent call last):
  File "/group/tools/Anaconda/Anaconda3-2019.10/envs/admix-kit/bin/admix", line 8, in <module>
    sys.exit(cli())
  File "/group/tools/Anaconda/Anaconda3-2019.10/envs/admix-kit/lib/python3.9/site-packages/admix/cli/__init__.py", line 39, in cli
    fire.Fire()
  File "/group/tools/Anaconda/Anaconda3-2019.10/envs/admix-kit/lib/python3.9/site-packages/fire/core.py", line 143, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/group/tools/Anaconda/Anaconda3-2019.10/envs/admix-kit/lib/python3.9/site-packages/fire/core.py", line 477, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/group/tools/Anaconda/Anaconda3-2019.10/envs/admix-kit/lib/python3.9/site-packages/fire/core.py", line 693, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/group/tools/Anaconda/Anaconda3-2019.10/envs/admix-kit/lib/python3.9/site-packages/admix/cli/lanc.py", line 135, in lanc_convert
    lanc = admix.io.read_rfmix(
  File "/group/tools/Anaconda/Anaconda3-2019.10/envs/admix-kit/lib/python3.9/site-packages/admix/io/_read.py", line 320, in read_rfmix
    assert np.all(df_indiv.index == lanc.columns)
AssertionError

Admix kit function:

admix lanc-convert \
  --pfile $pfilestem \
  --rfmix $mspchr1 \
  --out $out/test-lanc

Thanks,
Mike

**Comment by michaelofrancis** [comment]
Hi, I believe I have found the solution to this issue in case anyone else was wondering.

In order to generate the .lanc file, all these conditions must be true:
1. The .msp file and .psam file must have the same participants in the same order
2. .msp and .pgen must have chromosomes named in the same way (i.e. chr1 and chr1 or 1 and 1)
3. If the .msp file columns are named IID.0, IID.1, then the .psam file cannot have both FID and IID columns. If both the FID and IID are present in the .psam, they will be appended together like FID_IID and then not match the .msp file in the assert line cited in the above error at _read.py line 320 `assert np.all(df_indiv.index == lanc.columns)`

Thanks,
Mike

**Comment by KangchengHou** [comment]
Thanks @michaelofrancis! These are all correct - there must be exact matching between the PLINK2 files and local ancestry files. And PLINK2 can only have IID column in .psam files. Potentially we can modify the software to be more flexible with some of these requirements (I have been busy transitioning to a new position - sorry for the late reply)
